---
# This action performs a lint of files in the repository

# Name of the action
name: Linting

# Events which trigger the action
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  markdownlint:
    name: Lint repository files
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: PYTHONPATH=/workspaces/namedtuple-maker:/~.

    steps:
      # Checkout repository code
      # checkout@v2 action documentation
      # https://github.com/marketplace/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install testing packages
      - name: Install testing packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements/requirements.txt

      # Lint Python files with flake8
      - name: Lint Python files with flake8
        run: |
          flake8 . --count --show-source --statistics

      # Lint YAML files with yamllint
      - name: Lint YAML files yamllint
        run: |
          yamllint .

      # Static code analysis with bandit
      - name: Static code analysis with bandit
        run: |
          bandit -rc .bandit.yml .

      # Python application tests with pytest
      - name: Python application tests with pytest
        run: |
          export $PYTHONPATH:${{ env.PYTHONPATH }}
          pytest tests/

      # Lint markdown files
      # markdownlint-cli action documentation
      # https://github.com/marketplace/actions/markdownlint-cli
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
          config_file: .markdownlint.json
